interactions:
- request:
    body: '{"biller_id": 2901, "account_number": "1111322016"}'
    headers:
      Accept: [application/vnd.regalii.v3.1+json]
      Accept-Encoding: ['gzip, deflate']
      Authorization: ['APIAuth 88879c1b066dc9aea6201f27be2bbba9:z06iZr49HxaA6hrOLTAuJAdb6ZE=']
      Connection: [keep-alive]
      Content-Length: ['51']
      Content-MD5: [ZkNGR5IItPT5UO5fquuDpg==]
      Content-Type: [application/json]
      Date: ['Fri, 15 Feb 2019 00:13:55 GMT']
      User-Agent: [python-requests/2.21.0]
    method: POST
    uri: https://api.casiregalii.com/bills
  response:
    body: {string: '{"code":"R16","message":"Failed to make the consult, please try
        again later","id":8393}'}
    headers:
      Cache-Control: [no-cache]
      Connection: [keep-alive]
      Content-Type: [application/json; charset=utf-8]
      Date: ['Fri, 15 Feb 2019 00:13:56 GMT']
      Strict-Transport-Security: [max-age=31536000]
      Transfer-Encoding: [chunked]
      X-Content-Type-Options: [nosniff]
      X-Frame-Options: [SAMEORIGIN]
      X-Request-Id: [e1f301df-7e2d-4051-a2d8-b9ee74480811]
      X-Runtime: ['1.050771']
      X-XSS-Protection: [1; mode=block]
    status: {code: 422, message: Unprocessable Entity}
version: 1
